export const users = [
	{
		id: 1,
		name: "admin",
		role: "admin",
		email: "admin@example.com",
		password: "admin123",
	},
	{
		id: 2,
		name: "hamada",
		role: "seller",
		email: "hamada@example.com",
		password: "hamada123",
	},
	{
		id: 3,
		name: "ali",
		role: "customer",
		email: "ali@example.com",
		password: "ali123",
	},
];

export const products = [
	{
		id: 1,
		sellerEmail: "hamada@example.com",
		name: "laptop",
		price: 100,
		description: "Description for laptop",
		category: "smart devices",
		image: "/assests/images/product.png",
		fav: false,
		stock: 50,
		quantity: 1,
	},
	{
		id: 2,
		sellerEmail: "hamada@example.com",
		name: "smartphone",
		price: 200,
		description: "Description for smartphone",
		category: "smart devices",
		image: "/assests/images/product.png",
		fav: false,
		stock: 30,
		quantity: 1,
	},
	{
		id: 3,
		sellerEmail: "hamada@example.com",
		name: "tablet",
		price: 300,
		description: "Description for tablet",
		category: "smart devices",
		image: "/assests/images/product.png",
		fav: false,
		stock: 20,
		quantity: 1,
	},
	{
		id: 4,
		sellerEmail: "hamada@example.com",
		name: "smartwatch",
		price: 150,
		description: "Description for smartwatch",
		category: "smart devices",
		image: "/assests/images/product.png",
		fav: false,
		stock: 25,
		quantity: 1,
	},
	{
		id: 5,
		sellerEmail: "hamada@example.com",
		name: "wireless earbuds",
		price: 100,
		description: "Description for wireless earbuds",
		category: "smart devices",
		image: "/assests/images/product.png",
		fav: false,
		stock: 40,
		quantity: 1,
	},
];

export const orders = [
	{
		id: new Date().getTime(),
		customerEmail: "customer@example.com",
		cart: [
			{
				id: new Date().getTime(),
				sellerEmail: "hamada@example.com",
				name: "tablet",
				price: 300,
				description: "Description for tablet",
				category: "smart devices",
				image: "/assests/images/product.png",
				fav: false,
				stock: 20,
				quantity: 2,
			},
			{
				id: new Date().getTime(),
				sellerEmail: "hamada@example.com",
				name: "wireless earbuds",
				price: 100,
				description: "Description for wireless earbuds",
				category: "smart devices",
				image: "/assests/images/product.png",
				fav: false,
				stock: 40,
				quantity: 1,
			},
		],
		total: 400,
	},
];

export const currentUser = {
	id: 2,
	name: "hamada",
	role: "seller",
	email: "hamada@example.com",
	password: "hamada123",
};

export const favorites = [
	{
		id: 1,
		sellerEmail: "hamada@example.com",
		name: "laptop",
		price: 100,
		description: "Description for laptop",
		category: "smart devices",
		image: "url",
		stock: 50,
	},
	{
		id: 5,
		sellerEmail: "hamada@example.com",
		name: "wireless earbuds",
		price: 100,
		description: "Description for wireless earbuds",
		category: "smart devices",
		image: "url",
		stock: 40,
	},
];
